# Generated by Django 5.2 on 2025-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('billing_cycle', models.CharField(blank=True, max_length=50)),
                ('features', models.TextField(help_text='Separate features with newline')),
                ('cta_text', models.CharField(default='Get Started', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
