# Generated by Django 5.2 on 2025-04-11 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onTap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Waiting Subscriber',
                'verbose_name_plural': 'Waiting Subscribers',
            },
        ),
    ]
