# Generated by Django 5.2 on 2025-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onTap', '0002_waitingsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='yearly_billing_cycle',
            field=models.CharField(blank=True, default='/year', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='yearly_price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
